# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '10.0'
target 'Hospital' do
  use_frameworks!
    pod 'Kingfisher', '~> 3.0'
    pod 'Alamofire', '~> 4.4'
    pod 'ObjectMapper', '~> 2.2'
    pod "PromiseKit", "~> 4.0"
    pod 'RxSwift',    '~> 3.4.1'
    pod 'RxCocoa',    '~> 3.4.1'
   pod 'RxDataSources', '~> 1.0'
end
